// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string     `gorm:"column:username;not null" json:"username"`
	Password  string     `gorm:"column:password;not null" json:"password"`
	Status    int32      `gorm:"column:status;not null" json:"status"`
	CreatedAt *time.Time `gorm:"column:created_at;not null" json:"created_at" time_format:"sql_datetime"`
	UpdatedAt *time.Time `gorm:"column:updated_at;not null" json:"updated_at" time_format:"sql_datetime"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}


